### ISSUE TITLE
Upgrade to q5.js v2

### ISSUE THREAD

**Issue by quinton-ashley** [peilingjiang/b5#225]
I just found your project and I'm absolutely blown away by it! 🤩

I saw that three years ago you completed this task:

> Use a more efficient renderer, like native HTML canvas or q5.js

I'd like to let you know about q5.js v2, a fork and continuation of LingDong's q5xjs (v0) project that I'm working on.
https://q5js.org

I noticed that b5 is still in beta and you haven't worked on it in six months and before that it had been 3 years. Seems this was your capstone project at NYU. Do you plan on finishing it?

Young students would love this. I'd love to collaborate with you on this or get your permission to continue developing it.

**Comment by peilingjiang** [comment]
I'm glad that you find the project interesting. Unfortunately, I don't have much time to continue working on this project. For now, please feel free to extend the project in a fork, and I am more than happy to discuss collaboration opportunities to push this project further through email.

**Comment by quinton-ashley** [comment]
@peilingjiang Awesome! Here is my email: q5js.org@gmail.com
